name: Deploy to EC2

on:
  push:
    branches:
      - prod

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH key
      run: |
        echo "${{ secrets.EC2_SSH_KEY_BASE64 }}" | base64 --decode > private_key.pem
        chmod 600 private_key.pem

    - name: SSH into EC2 and deploy
      run: |
        sudo ssh -i private_key.pem -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
          cd app/atendente-bot
          git pull origin prod
          sudo docker compose down
          echo "${{ secrets.PRODUCTION_ENVS }}" > .env.production
          sudo docker compose up -d
        EOF
