name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH key
      run: |
        # Verifique se a secret foi recuperada corretamente
        echo "Secret EC2_SSH_KEY_BASE64 is available."
        
        # Cria o arquivo de chave privada a partir da chave codificada em base64
        echo "${{ secrets.EC2_SSH_KEY_BASE64 }}" | base64 --decode > private_key.pem
        
        # Ajusta as permissões da chave privada
        chmod 600 private_key.pem
        
        # Verifica se a chave privada foi criada corretamente
        ls -l private_key.pem
        
        # Inicia o agente SSH e adiciona a chave privada
        eval $(ssh-agent -s)
        ssh-add private_key.pem

    - name: SSH into EC2 and deploy
      run: |
        echo "Trying to SSH into EC2..."
        ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
          cd /path/to/your/project
          git pull origin main
          docker-compose down
          docker-compose up -d
        EOF
